apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8161
      targetPort: http
      name: http
    - port: 61616
      targetPort: netty
      protocol: TCP
      name: netty
    - port: 5672
      targetPort: amqp
      name: amqp
    - port: 61613
      targetPort: stomp
      name: stomp
    - port: 1883
      targetPort: mqtt
      name: mqtt
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}
